package:
    type:           yii2-extension
    name:           hipanel-module-client
    namespace:      hipanel\modules\client
    headline:       HiPanel Client Module
    title:          Client module for HiPanel
    keywords:       client, hipanel, plugin
    description:    |
        [![Logo](https://raw.githubusercontent.com/hiqdev/hipanel-core/master/docs/logo.png)](https://hipanel.com/)

        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.
        This package provides client management for HiPanel.

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
