package:
    name:           hipanel-module-client
    namespace:      hipanel\modules\client
    label:          HiPanel ClientModule
    title:          Client Plugin for HiPanel
    type:           yii2-extension
    keywords:       client, hipanel, plugin
    year:           2014

require:
    hiqdev/hidev-config-php:    "*@dev"
